CREATE SEQUENCE MESA_ID_SEQ;
CREATE SEQUENCE VENDAS_ID_SEQ;
CREATE SEQUENCE ITENS_VENDAS_ID_SEQ;
CREATE SEQUENCE PRODUTO_ID_SEQ;
CREATE SEQUENCE FUNCIONARIO_ID_SEQ;
CREATE SEQUENCE COMISSOES_ID_SEQ;

