-- CONSULTANDO REGISTROS
SELECT * FROM MESAS;
SELECT MESA_CODIGO, DATA_CRIACAO FROM MESAS;
SELECT * FROM MESAS WHERE MESA_CODIGO = '00002';
UPDATE PRODUTOS SET PRODUTO_VALOR = 4 WHERE ID = 2;
UPDATE PRODUTOS SET DATA_CRIACAO = '31/12/2016';
SELECT DATA_CRIACAO FROM PRODUTOS;
DELETE FROM MESAS WHERE ID = 2;
