-- CRIANDO SEQUENCIAS
CREATE SEQUENCE MESA_ID_SEQ;
CREATE SEQUENCE VENDAS_ID_SEQ;
CREATE SEQUENCE ITENS_VENDAS_ID_SEQ;
CREATE SEQUENCE PRODUTOS_ID_SEQ;
CREATE SEQUENCE FUNCIONARIO_ID_SEQ;
CREATE SEQUENCE COMISSOES_ID_SEQ;

-- VINCULANDO SEQUENCIAS AS TABELAS
ALTER TABLE MESAS 
ALTER COLUMN ID SET DEFAULT NEXTVAL('MESA_ID_SEQ');
ALTER TABLE VENDAS 
ALTER COLUMN ID SET DEFAULT NEXTVAL('VENDAS_ID_SEQ');
ALTER TABLE ITENS_VENDAS 
ALTER COLUMN ID SET DEFAULT NEXTVAL('ITENS_VENDAS_ID_SEQ');
ALTER TABLE PRODUTOS 
ALTER COLUMN ID SET DEFAULT NEXTVAL('PRODUTOS_ID_SEQ');
ALTER TABLE FUNCIONARIOS 
ALTER COLUMN ID SET DEFAULT NEXTVAL('FUNCIONARIO_ID_SEQ');
ALTER TABLE COMISSOES 
ALTER COLUMN ID SET DEFAULT NEXTVAL('COMISSOES_ID_SEQ');
